homeassistant:
  customize:
    camera.intercom:
      friendly_name: "Входная дверь"


beward:
  devices:
    - host: !secret camera_doorbell_host
      username: !secret camera_doorbell_login
      password: !secret camera_doorbell_password
      stream: 1
      name: "Front door"


camera:
  - platform: beward


binary_sensor:
  - platform: beward


sensor:
  - platform: beward


automation:
  - alias: "[Security] Front door Ding"
    trigger:
      platform: state
      entity_id: binary_sensor.front_door_ding
      to: 'on'
    action:
      # - delay: 00:00:01
      - service: notify.limych
        data:
          message: "Звонят в дверь!"
          data:
            photo:
              file: /config/.storage/beward/front_door_last_ding.jpg
              caption: "Звонят в дверь!"
