title: Settings
icon: mdi:cogs
path: settings
panel: true
cards:
  - type: vertical-stack
    cards:
      - type: custom:compact-custom-header
      - type: custom:layout-card
        cards:
          - type: custom:tracker-card
            title:
            trackers:
              - sensor.custom_card_tracker
              - sensor.custom_component_tracker

          # - type: custom:home-setter
          #   pages:
          #     - name: Default
          #       path: lovelace/home
          #     - name: Dashboard
          #       path: lovelace/dashboard

          - type: vertical-stack
            cards:
              - !include dev_card_content.yaml
              - type: custom:monster-card
                show_empty: false
                card:
                  type: entities
                  title: "Debugging"
                  show_header_toggle: false
                filter:
                  include:
                    - entity_id: input_boolean.test
                    - entity_id: "*_alert_level"
                      options:
                        secondary_info: last-changed

          - type: history-graph
            title: "Temperature 48h"
            hours_to_show: 48
            entities:
              - entity: sensor.gismeteo_temperature
                name: "Outdoor Temperature"
              - sensor.average_temperature
          - type: history-graph
            title: "Temperature 48h"
            hours_to_show: 48
            entities:
              - sensor.gismeteo_temperature
              - sensor.owm_temperature
              - sensor.average_temperature_test

          - !include links_card.yaml

          # - type: custom:auto-entities
          #   card:
          #     type: entities
          #     head:
          #       type: section
          #       label: "Power consumption"
          #   filter:
          #     include:
          #       - entity_id: sensor.daily_energy_consumption
          #       - entity_id: sensor.monthly_energy_consumption
          #       - entity_id: "*_power"
          #     exclude:
          #       - entity_id: "*_2"
          #       - entity_id: "*_management"

          - type: custom:auto-entities
            card:
              type: entities
              title: "Battery warning"
            filter:
              include:
                - domain: device_tracker
                  options:
                    secondary_info: last-changed
                  attributes:
                    battery: "< 50"
                    source_type: gps

          # - type: vertical-stack
          #   cards:
          #     - type: custom:monster-card
          #       show_empty: false
          #       card:
          #         type: entities
          #         title: "Batteries"
          #         show_header_toggle: false
          #       filter:
          #         include:
          #           - entity_id: "*battery*"
          #           - attributes:
          #               battery: '< 50'
          #           - attributes:
          #               battery_level: '< 50'
          #         exclude:
          #           - domain: alert
          #           - domain: automation
          #           - domain: group
          #           - entity_id: "*pressure*"
          #           - entity_id: "*humidity*"

          - type: vertical-stack
            cards:
              - type: custom:monster-card
                show_empty: false
                card:
                  type: entities
                  title: "Things that are probably broken"
                  show_header_toggle: false
                filter:
                  include:
                    - state: "unknown"
                    - state: "unavailable"
                  exclude:
                    - domain: group
                    - domain: input_text
                    - domain: history_graph
                    - entity_id: customizer.customizer
