language: python
python:
  - 3.7
env:
  - BUILD=stable
  - BUILD=beta
  - BUILD=dev
matrix:
  allow_failures:
    - python: 3.7
      env: BUILD=dev

before_install:
  - mv tests/fake_secrets.yaml secrets.yaml
  - perl -i -pe 'if (/whitelist_external_dirs:/) { $_ = <>; $_ = <> while /^\s*-/; }' configuration.yaml
  - sed -i 's|use_x_forwarded_for:.*||g; s|trusted_proxies:.*||g' configuration.yaml
  # - perl -i -pe 'while (/- platform: rpi_gpio/) { $_ = <>; $_ = <> while !/^\s*-/ && !eof(); }' packages/areas/hallway.yaml
  - rm packages/areas/hallway.yaml
install:
  - if [ $BUILD == "beta" ]; then
      pip3 install --pre homeassistant;
    elif [ $BUILD == "dev" ]; then
      pip3 install git+git://github.com/home-assistant/home-assistant.git@dev;
    else
      pip3 install homeassistant;
    fi
script:
  - hass -c . --script check_config
