# Update SSL certificates from NAS
- id: ssl_update
  alias: Update SSL certificates
  initial_state: True
  trigger:
  - platform: time
    at: '00:00:00'
  action:
  - service: shell_command.cert_update

- alias: Good Night
  trigger: 
  - platform: state
    entity_id: input_boolean.goodnight_switch
    to: 'on'
  action:
  - service: input_select.select_option
    entity_id: input_select.house_mode
    data:
      option: 'Night'
  - service: input_boolean.turn_off
    entity_id: input_boolean.goodmorning_switch

- alias: Good Night - Off
  trigger: 
  - platform: state
    entity_id: binary_sensor.dark_outside
    to: 'off'
  action:
  - service: input_boolean.turn_off
    entity_id: input_boolean.goodnight_switch

- alias: Good Morning
  trigger: 
  - platform: state
    entity_id: input_boolean.goodmorning_switch
    to: 'on'
  action:
  - service: input_select.select_option
    entity_id: input_select.house_mode
    data:
      option: 'Home'
  - service: input_boolean.turn_off
    entity_id: input_boolean.goodnight_switch

- alias: Good Morning - Off
  trigger: 
  - platform: state
    entity_id: input_boolean.goodmorning_switch
    to: 'on'
    for:
      hours: 3
  - platform: time
    at: '12:00:00'
  action:
  - service: input_boolean.turn_off
    entity_id: input_boolean.goodmorning_switch

##########################################
## Setting Security Mode
##########################################
- alias: Security - Arming
  trigger: 
  - platform: state
    entity_id: input_select.house_mode
    from: 'Home'
  action:
  - service: input_select.select_option
    entity_id: input_select.security_system
    data:
      option: 'Armed'

- alias: Security - Disarming
  trigger: 
  - platform: state
    entity_id: input_select.house_mode
    to: 'Home'
  condition:
  - condition: state
    entity_id: binary_sensor.presence
    state: 'on'
  action:
  - service: input_select.select_option
    entity_id: input_select.security_system
    data:
      option: 'Disarmed'

##########################################
## Setting House Mode based on Presence
##########################################
- alias: Home Mode - Leaving
  trigger:
  - platform: state
    entity_id: binary_sensor.presence
    to: 'off'
    for:
      seconds: 15
  condition:
  - condition: numeric_state
    entity_id: sensor.ha_runtime_in_minutes
    above: 1
  - condition: state
    entity_id: input_select.house_mode
    state: 'Home'
  action:
  - service: input_select.select_option
    entity_id: input_select.house_mode
    data:
      option: 'Away'

- alias: Home Mode - Arriving
  trigger:
  - platform: state
    entity_id: binary_sensor.presence
    to: 'on'
  condition:
  - condition: numeric_state
    entity_id: sensor.ha_runtime_in_minutes
    above: 1
  - condition: state
    entity_id: input_select.house_mode
    state: 'Away'
  action:
  - service: input_select.select_option
    entity_id: input_select.house_mode
    data:
      option: 'Home'

- alias: Mark house as Vacation Mode
  trigger:
  - platform: state
    entity_id: binary_sensor.presence
    to: 'off'
    for:
      hours: 24
  action:
  - service: input_boolean.turn_on
    entity_id: input_boolean.vacation_mode

- alias: Home Mode - Night
  trigger: 
  - platform: state
    entity_id: input_select.house_mode
    to: 'Night'
  action:
  - service: media_player.media_pause
#    entity_id: ...  # Default to All

- alias: Home Mode - Morning
  trigger: 
  - platform: state
    entity_id: input_select.house_mode
    from: 'Night'
    to: 'Home'
  action:
  - service: media_player.media_play
#    entity_id: ...  # Default to All
