homeassistant:
  # Name of the location where Home Assistant is running
  name: !secret home_title
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret home_elevation
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: !secret home_timezone
  whitelist_external_dirs:
    - /tmp
    - /config/.storage/beward
    - /config/www
  packages: !include_dir_named packages
  # Customization
  auth_providers:
    - type: homeassistant
    - type: trusted_networks
      trusted_networks:
        - 127.0.0.1
        - "::1"
        - "fd00::/8"
        # - !secret trusted_network_1
        # - !secret trusted_network_2
  customize_glob:
    "*.*":
      custom_ui_state_card: state-card-custom-ui
    "group.*":
      hide_control: true

# Load basic components
system_health:
updater:
auth:
api:
config:
upnp:
  port_mapping: true
discovery:
ssdp:
zeroconf:
#  sensors: false
http:
  base_url: !secret hass_base_url
  ssl_certificate: !secret ssl_certificate
  ssl_key: !secret ssl_key
  trusted_proxies: !secret gateway_host_ip
  use_x_forwarded_for: true
customizer:
  custom_ui: hosted
mobile_app:
hacs:
  token: !secret hacs_github_token
  appdaemon: true


# ########################################
# ###                GUI               ###
# ########################################

lovelace:
  mode: yaml
frontend:   # Enables the frontend
  javascript_version: latest
  themes: !include_dir_merge_named themes/
map:

#panel_custom: !include panels/panel_custom.yaml
panel_iframe: !include panels/panel_iframe.yaml

# ########################################
# ###              LOGGING             ###
# ########################################

recorder:
  db_url: !secret db_url
  purge_interval: 2
  purge_keep_days: 12
history: !include logging/history.yaml
logbook: !include logging/logbook.yaml
logger: !include logging/logger.yaml


# ########################################
# ###             SERVICES             ###
# ########################################

sun:
#shopping_list:

# Devices tracking
zone: !include_dir_merge_list zones/
owntracks:
  max_gps_accuracy: 200
mqtt:
  broker: !secret mqtt_host_ip
  username: !secret mqtt_username
  password: !secret mqtt_password
  client_id: !secret home_title
  discovery: true

# scene: !include_dir_list scenes/
