homeassistant:
  # Name of the location where Home Assistant is running
  name: !secret home_title
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret home_elevation
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: !secret home_timezone
  whitelist_external_dirs:
    - /tmp
    - /config/.storage/beward
  packages: !include_dir_named packages
  # Customization
  auth_providers:
    - type: homeassistant
    - type: trusted_networks
      trusted_networks:
        - 127.0.0.1
        - ::1
        - 192.168.1.0/24
        - fd00::/8
        - !secret work_office_ip
  customize_glob:
    "*.*":
      custom_ui_state_card: state-card-custom-ui
    "group.*":
      hide_control: true

# Load basic components
system_health:
updater:
auth:
api:
config:
upnp:
  port_mapping: true
discovery:
ssdp:
zeroconf:
#  sensors: false
http:
  base_url: !secret hass_base_url
  ssl_certificate: !secret ssl_certificate
  ssl_key: !secret ssl_key
  ip_ban_enabled: true
  login_attempts_threshold: 7
customizer:
  custom_ui: hosted


# ########################################
# ###                GUI               ###
# ########################################

lovelace:
  mode: yaml
frontend:   # Enables the frontend
  javascript_version: latest
  themes: !include_dir_named themes/
map:

#panel_custom: !include panels/panel_custom.yaml
panel_iframe: !include panels/panel_iframe.yaml

custom_updater:
  track:
    - cards
    - components
    - python_scripts
  card_urls:
    - https://raw.githubusercontent.com/atomic7777/atomic_calendar/master/tracker.json
    - https://raw.githubusercontent.com/dnguyen800/Air-Visual-Card/master/tracker.json
    - https://raw.githubusercontent.com/kalkih/mini-graph-card/master/tracker.json
    - https://raw.githubusercontent.com/kalkih/mini-media-player/master/tracker.json
    - https://raw.githubusercontent.com/matisaul/vertical-style-card/master/tracker.json
    - https://raw.githubusercontent.com/MizterB/lovelace-secondaryinfo-entity-row/master/custom_cards.json
    - https://raw.githubusercontent.com/sgttrs/lovelace-weather-card-chart/master/custom-updater.json
  component_urls:
    - https://raw.githubusercontent.com/Limych/HomeAssistantComponents/master/custom_components.json
    - https://raw.githubusercontent.com/Limych/media_player.linkplay/master/custom_components.json
    - https://raw.githubusercontent.com/marcogazzola/custom_components/master/custom_components.json
  python_script_urls:
    - https://raw.githubusercontent.com/bieniu/home-assistant-config/master/python_scripts/python_scripts.json   

# ########################################
# ###              LOGGING             ###
# ########################################

recorder:
  db_url: !secret db_url
  purge_interval: 2
  purge_keep_days: 12
history: !include logging/history.yaml
logbook: !include logging/logbook.yaml
logger: !include logging/logger.yaml


# ########################################
# ###              ENTITIES            ###
# ########################################

zone: !include_dir_merge_list zones/

# Torrents
# transmission:
#   host: !secret transmission_host
#   username: !secret transmission_username
#   password: !secret transmission_password
#   turtle_mode: true
#   monitored_conditions:
#     - current_status
#     - download_speed
#     - upload_speed


# ########################################
# ###             SERVICES             ###
# ########################################

sun:
#shopping_list:

# Devices tracking
owntracks:
  max_gps_accuracy: 200
mqtt:
  broker: !secret mqtt_host_ip
  username: !secret mqtt_username
  password: !secret mqtt_password
  client_id: !secret home_title
  discovery: true

scene: !include_dir_list scenes/
