homeassistant:
  # Name of the location where Home Assistant is running
  name: !secret home_title
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret home_elevation
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: !secret home_timezone
  #    whitelist_external_dirs:
  #      - '/config/www/motion'
  # Customization
  customize_glob: !include customglob.yaml
  customize: !include customize.yaml
  packages: !include_dir_named packages
config:   # Enables configuration UI
auth:
api:
wake_on_lan:
upnp:
  port_mapping: true
#  sensors: false
http:
  base_url: !secret hass_base_url
  ssl_certificate: /ssl/fullchain.cer
  ssl_key: /ssl/privkey.key
  ip_ban_enabled: true
  login_attempts_threshold: 3
  trusted_networks:
    - 127.0.0.1
    - 192.168.1.1

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
# Optional, allows Home Assistant developers to focus on popular components.
# include_used_components: true
customizer:
  custom_ui: hosted

#google:
#  client_id: !secret google_client_id
#  client_secret: !secret google_client_secret


# ########################################
# ###                GUI               ###
# ########################################

lovelace:
#  mode: yaml
map:   # Enables a map showing the location of tracked devices
frontend:   # Enables the frontend
  javascript_version: latest
  themes: !include_dir_named themes/

#panel_custom: !include panels/panel_custom.yaml
#panel_iframe: !include panels/panel_iframe.yaml

custom_updater:
  track:
    - cards
    - components
  card_urls:
    - https://raw.githubusercontent.com/kalkih/mini-media-player/master/tracker.json
    - https://raw.githubusercontent.com/kalkih/mini-graph-card/master/tracker.json


# ########################################
# ###              LOGGING             ###
# ########################################

recorder: !include logging/recorder.yaml
history: !include logging/history.yaml
logbook: !include logging/logbook.yaml
logger: !include logging/logger.yaml


# ########################################
# ###              ENTITIES            ###
# ########################################

media_player: !include entities/media_player.yaml
device_tracker: !include entities/device_tracker.yaml
zone: !include_dir_merge_list zones/


# ########################################
# ###             SERVICES             ###
# ########################################

sun:   # Track the sun
#shopping_list:

# Devices tracking
discovery:   # Discover some devices automatically
owntracks:   # OwnTracks device tracker
mqtt:
  broker: localhost
  discovery: true

# Notifications
telegram_bot: !include notify/telegram.yaml
notify: !include notify/notify.yaml

python_script:

tts:
  - platform: google

ffmpeg:
  ffmpeg_bin: /usr/bin/ffmpeg

shell_command:
  lovelace_gen: 'python /config/lovelace-gen.py > /config/lovelace-gen.log'
  cert_update: "bash /config/scripts/cert_update"





binary_sensor: !include binary_sensors.yaml
sensor: !include sensors.yaml
input_select: !include input_selects.yaml
# input_text: !include input_texts.yaml
# input_datetime: !include input_datetimes.yaml
input_boolean: !include input_booleans.yaml
group: !include groups.yaml
automation: !include_dir_merge_list automations/
#script: !include scripts.yaml
# alert: !include alerts.yaml
camera: !include cameras.yaml
scene: !include_dir_list scenes/
