homeassistant:
  # Name of the location where Home Assistant is running
  name: !secret home_title
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret home_elevation
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: !secret home_timezone
#  whitelist_external_dirs:
#    - '/config/www/motion'
  packages: !include_dir_named packages
  # Customization
  customize_glob: !include customglob.yaml
  customize: !include customize.yaml

# Load basic components
system_health:
updater:
auth:
api:
config:
upnp:
  port_mapping: true
#  sensors: false
http:
  base_url: !secret hass_base_url
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
  ip_ban_enabled: true
  login_attempts_threshold: 3
  trusted_networks:
    - 127.0.0.1
    - 192.168.1.1
customizer:
  custom_ui: hosted

#google:
#  client_id: !secret google_client_id
#  client_secret: !secret google_client_secret


# ########################################
# ###                GUI               ###
# ########################################

lovelace:
  mode: yaml
frontend:   # Enables the frontend
  javascript_version: latest
  themes: !include_dir_named themes/
map:

#panel_custom: !include panels/panel_custom.yaml
panel_iframe: !include panels/panel_iframe.yaml

custom_updater:
  card_urls:
    - https://raw.githubusercontent.com/MizterB/lovelace-secondaryinfo-entity-row/master/custom_cards.json
    - https://raw.githubusercontent.com/kalkih/mini-graph-card/master/tracker.json
    - https://raw.githubusercontent.com/kalkih/mini-media-player/master/tracker.json


# ########################################
# ###              LOGGING             ###
# ########################################

recorder: !include logging/recorder.yaml
history: !include logging/history.yaml
logbook: !include logging/logbook.yaml
logger: !include logging/logger.yaml


# ########################################
# ###              ENTITIES            ###
# ########################################

discovery:
person:
zone: !include_dir_merge_list zones/
device_tracker: !include entities/device_tracker.yaml
binary_sensor: !include entities/binary_sensors.yaml
sensor: !include entities/sensors.yaml

# Torrents
transmission:
  host: !secret transmission_host
  turtle_mode: true
  monitored_conditions:
    - current_status
    - download_speed
    - upload_speed


# ########################################
# ###             SERVICES             ###
# ########################################

sun:
#shopping_list:

# Devices tracking
owntracks:   # OwnTracks device tracker
mqtt:
  broker: a0d7b954-mqtt
  username: !secret mqtt_username
  password: !secret mqtt_password
  client_id: !secret home_title

# Notifications
telegram_bot: !include notify/telegram.yaml
notify: !include notify/notify.yaml
#alert: !include_dir_merge_named notify/alerts/

#tts:
#  - platform: google

scene: !include_dir_list scenes/
