resources:
  - url: /customcards/custom-lovelace/card-tools.js?track=true
    type: js
  - url: https://unpkg.com/moment@2.22.2/moment.js
    type: js
  - url: https://fonts.googleapis.com/css?family=Roboto+Condensed
    type: css

  - url: /customcards/custom-lovelace/air-visual-card.js?track=true
    type: js
  # - url: /customcards/custom-lovelace/alarm_control_panel-card.js
  #   type: js
  # - url: /customcards/custom-lovelace/atomic-calendar.js?track=true
  #   type: module
  - url: /customcards/custom-lovelace/auto-entities.js?track=true
    type: js
  # - url: /customcards/custom-lovelace/bar-card.js?track=true
  #   type: js
  - url: /customcards/custom-lovelace/bignumber-card.js
    type: js
  - url: /customcards/custom-lovelace/button-card.js?track=true
    type: module
  # - url: /customcards/custom-lovelace/calendar-card.js
  #   type: module
  # - url: /customcards/custom-lovelace/camera-card.js?track=true
  #   type: module
  - url: /customcards/custom-lovelace/card-modder.js?track=true
    type: js
  - url: /customcards/custom-lovelace/compact-custom-header.js?track=true
    type: module
  - url: /customcards/custom-lovelace/custom-weather-card-chart.js?track=false
    type: module
  # - url: /customcards/custom-lovelace/dual-gauge-card.js
  #   type: js
  # - url: /customcards/custom-lovelace/entity-attributes-card.js
  #   type: js
  - url: /customcards/custom-lovelace/fold-entity-row.js?track=true
    type: js
  # - url: /customcards/custom-lovelace/home-setter.js?track=true
  #   type: js
  - url: /customcards/custom-lovelace/layout-card.js?track=true
    type: js
  # - url: /customcards/custom-lovelace/light-card.js
  #   type: js
  - url: /customcards/custom-lovelace/live-camera-card.js?v.0.0.3
    type: module
  - url: /customcards/custom-lovelace/markdown-mod.js?track=true
    type: module
  - url: /customcards/custom-lovelace/mini-graph-card-bundle.js?track=true
    type: module
  - url: /customcards/custom-lovelace/mini-media-player-bundle.js?track=true
    type: module
  - url: /customcards/custom-lovelace/monster-card.js?track=true
    type: js
  - url: /customcards/custom-lovelace/popup-card.js?track=true
    type: js
  - url: /customcards/custom-lovelace/secondaryinfo-entity-row.js?track=true
    type: js
  - url: /customcards/custom-lovelace/state-attribute-element.js?track=true
    type: js
  # - url: /customcards/custom-lovelace/state-element.js
  #   type: js
  # - url: /customcards/custom-lovelace/state-switch.js
  #   type: js
  - url: /customcards/custom-lovelace/text-element.js?track=true
    type: js
  # - url: /customcards/custom-lovelace/toggle-lock-entity-row.js
  #   type: js
  - url: /customcards/custom-lovelace/tracker-card.js?track=true
    type: module
  # - url: /customcards/custom-lovelace/upcoming-media-card.js
  #   type: js
  # - url: /customcards/custom-lovelace/username-element.js
  #   type: js
  - url: /customcards/custom-lovelace/vertical-style-card.js?track=true
    type: js
    
title: Home
cch:
  disable: false
  header: true
  background_image: false
  menu: show
  notifications: show
  voice: hide
  options: clock
  clock_format: 24
  swipe: true
  swipe_animate: swipe
views:
  - !include lovelace/00_home_view.yaml
  - !include lovelace/10_home_info_view.yaml
  # - !include lovelace/20_lights_view.yaml
  - !include lovelace/30_system_info_view.yaml
  # - !include lovelace/31_system_graphs.yaml
  - !include lovelace/40_camera_view.yaml
  # - !include lovelace/60_traffic_view.yaml
  - !include lovelace/80_automations_view.yaml
  # - !include lovelace/101_dashboard.yaml
  # - !include lovelace/areas.yaml

  - !include lovelace/90_settings_view.yaml
  - !include lovelace/99_test_view.yaml
