resources:
  - url: /community_plugin/lovelace-card-tools/card-tools.js
    type: module
  - url: https://unpkg.com/moment@2.22.2/moment.js
    type: js
  - url: https://fonts.googleapis.com/css?family=Roboto+Condensed
    type: css

  - url: /community_plugin/air-visual-card/air-visual-card.js
    type: js
  # - url: /community_plugin/alarm_control_panel-card.js
  #   type: js
  # - url: /community_plugin/atomic-calendar.js
  #   type: module
  - url: /community_plugin/lovelace-auto-entities/auto-entities.js
    type: module
  # - url: /community_plugin/bar-card.js
  #   type: js
  - url: /community_plugin/bignumber-card/bignumber-card.js
    type: js
  - url: /community_plugin/button-card/button-card.js
    type: module
  # - url: /community_plugin/calendar-card.js
  #   type: module
  - url: /community_plugin/lovelace-card-mod/card-mod.js
    type: module
  - url: /community_plugin/compact-custom-header/compact-custom-header.js
    type: module
  - url: /local/custom-lovelace/custom-weather-card-chart.js
    type: module
  # - url: /community_plugin/dual-gauge-card.js
  #   type: js
  # - url: /community_plugin/entity-attributes-card.js
  #   type: js
  - url: /community_plugin/flex-horseshoe-card/flex-horseshoe-card.js
    type: module
  - url: /community_plugin/lovelace-fold-entity-row/fold-entity-row.js
    type: js
  - url: /community_plugin/lovelace-layout-card/layout-card.js
    type: module
  # - url: /community_plugin/light-card.js
  #   type: js
  # - url: /community_plugin/live-camera-card.js?v.0.0.3
  #   type: module
  - url: /community_plugin/mini-graph-card/mini-graph-card-bundle.js
    type: module
  - url: /community_plugin/mini-media-player/mini-media-player-bundle.js
    type: module
  - url: /local/custom-lovelace/popup-card.js
    type: js
  - url: /community_plugin/secondaryinfo-entity-row/secondaryinfo-entity-row.js
    type: js
  - url: /community_plugin/state-attribute-element/state-attribute-element.js
    type: js
  # - url: /community_plugin/state-element.js
  #   type: js
  # - url: /community_plugin/state-switch.js
  #   type: js
  - url: /community_plugin/text-element/text-element.js
    type: js
  # - url: /community_plugin/toggle-lock-entity-row.js
  #   type: js
  # - url: /community_plugin/upcoming-media-card.js
  #   type: js
  # - url: /community_plugin/username-element.js
  #   type: js
  - url: /local/custom-lovelace/vertical-style-card.js
    type: js
    
title: Home
cch:
  disable: false
  header: true
  background_image: false
  menu: show
  notifications: show
  voice: hide
  options: clock
  clock_format: 24
  swipe: true
  swipe_animate: swipe
views:
  - !include lovelace/00_home_view.yaml
  - !include lovelace/05_weather_view.yaml
  - !include lovelace/10_home_info_view.yaml
  # - !include lovelace/20_lights_view.yaml
  - !include lovelace/30_system_info_view.yaml
  # - !include lovelace/31_system_graphs.yaml
  - !include lovelace/40_security_view.yaml
  # - !include lovelace/60_traffic_view.yaml
  - !include lovelace/80_automations_view.yaml
  # - !include lovelace/101_dashboard.yaml
  # - !include lovelace/areas.yaml

  - !include lovelace/90_settings_view.yaml
  - !include lovelace/99_test_view.yaml
