homeassistant:
  customize:
    binary_sensor.limych_sleeping:
      friendly_name: "Лимыч спит"
      icon: mdi:sleep
    device_tracker.limych_presence:
      friendly_name: "Присутствие Лимыча"
      icon: mdi:map-marker-circle
    sensor.limych_ahphonem_battery_level:
      friendly_name: "Заряд батареи AH-Phone M"
      icon: mdi:battery-30

  customize_glob:
    sensor.*battery*:
      unit_of_measurement: '%'
      templates:
        hs_color: >-
          if (state > 50) return [0, 0];
          else if (state > 25) return [40, 70];
          else return [0, 85];


binary_sensor:
  - platform: mqtt
    name: limych_sleeping
    state_topic: 'sleep/limych/tracking'


sensor:
  - platform: template
    sensors:
      limych_ahphonem_battery_level:
        value_template: >-
          {{ state_attr('device_tracker.limych_ahphonem','battery') }}
