homeassistant:
  customize_glob:
    sensor.*_humidity:
      device_class: humidity
      unit_of_measurement: '%'
    sensor.*_temperature:
      device_class: temperature
      unit_of_measurement: '°C'

  customize:
    sensor.bathroom_temperature:
      friendly_name: "Ванная"
    sensor.bathroom_humidity:
      friendly_name: "Ванная"


switch:
  - platform: mqtt
    name: "Bathroom Fan"
    state_topic: "bathroom/relay/state"
    command_topic: "bathroom/gpio/12"
    payload_on: "1"
    payload_off: "0"
    qos: 1
    retain: true
    availability_topic: "bathroom/status/LWT"


sensor:
  - platform: mqtt
    name: "Bathroom Temperature"
    state_topic: "bathroom/sensor/temperature"
    availability_topic: "bathroom/status/LWT"
    expire_after: 300
    device_class: temperature
    unit_of_measurement: "°C"

  - platform: mqtt
    name: "Bathroom Humidity"
    state_topic: "bathroom/sensor/humidity"
    availability_topic: "bathroom/status/LWT"
    expire_after: 300
    device_class: humidity
    unit_of_measurement: "%"


input_boolean:
  bathroom_drying:
    name: "Сушка белья"
    icon: mdi:tumble-dryer


automation:
  - alias: '[House] Bathroom Drying On'
    initial_state: 'on'
    trigger:
      - platform: numeric_state
        entity_id: sensor.bathroom_humidity
        above: 55
    condition:
      - condition: state
        entity_id: input_boolean.bathroom_drying
        state: 'on'
    action:
      - service: switch.turn_on
        entity_id: switch.bathroom_fan

  - alias: '[House] Bathroom Drying Off'
    initial_state: 'on'
    trigger:
      - platform: numeric_state
        entity_id: sensor.bathroom_humidity
        below: 50
    condition:
      - condition: state
        entity_id: input_boolean.bathroom_drying
        state: 'on'
    action:
      - service: switch.turn_off
        entity_id: switch.bathroom_fan

  - alias: '[House] Bathroom Drying Mode AutoOff'
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: input_boolean.bathroom_drying
        to: 'on'
        for:
          hours: 5
    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.bathroom_drying
