- platform: template
  sensors:
    dark_outside:
      friendly_name: "Темно на улице"
      value_template: >
        {{ is_state('sun.sun', 'below_horizon') }}

    presence:
      friendly_name: "Люди в Доме"
      device_class: occupancy
      value_template: >
        {{ is_state('binary_sensor.presence_owners', 'on')
        or is_state('binary_sensor.presence_guests', 'on') }}
#        or is_state('binary_sensor.presence_guests', 'on')
#        or is_state('group.motion', 'on') }}

    presence_owners:
      friendly_name: "Хозяева в Доме"
      device_class: occupancy
      value_template: >
        {{ is_state('group.owners', 'home') }}

    presence_guests:
      friendly_name: "Гости в Доме"
      device_class: occupancy
      value_template: >
        {{ is_state('input_boolean.guest_mode', 'on')
        or is_state('group.guests', 'home') }}

# - platform: workday
#  country: RU
