- platform: ffmpeg
  name: "Входная дверь"
  input: -rtsp_transport tcp -i rtsp://hass:321ewq@192.168.1.90:554/av0_1
- platform: onvif
  name: "Входная дверь"
  host: 192.168.1.90
  port: 2000
#  username: hass
#  password: 321ewq
  username: !secret camera_doorbell_login
  password: !secret camera_doorbell_password
