- platform: linkplay
  name: Kitchen
  host: !secret speaker_kitchen_host
  lastfm_api_key: !secret lastfm_apikey

- platform: linkplay
  name: 'Living Room'    # As Slave
  host: !secret speaker_kitchen_host
  lastfm_api_key: !secret lastfm_apikey

#- platform: emby
#  host: !secret emby_host
#  api_key: !secret emby_apikey
#  auto_hide: true
