- platform: uptime
  name: Uptime
  unit_of_measurement: minutes

# Time-Date Sensor
- platform: time_date
  display_options:
    - 'time'
    - 'date'
    - 'date_time'
#    - 'time_date'

# Weather prediction
#  - platform: yr
#    Name: Погода

- platform: openweathermap
  api_key: !secret openweathermap_apikey
  language: ru
  forecast: true
  monitored_conditions:
    - weather
    - temperature
    - wind_speed
    - wind_bearing
    - humidity
    - pressure
    - clouds
    - rain
    - snow
    - weather_code

# Sonarr
- platform: sonarr
  host: !secret sonarr_host
  api_key: !secret sonarr_apikey
  days: 3

# 17track packages tracker
- platform: seventeentrack
  username: !secret seventeentrack_email
  password: !secret seventeentrack_password

# Last.fm
- platform: lastfm
  api_key: !secret lastfm_apikey
  users:
    - Limych

# MQTT sensors
#- platform: mqtt
#  state_topic: "owntracks/username/deviceid"
#  name: "Battery Tablet"
#  unit_of_measurement: "%"
#  value_template: '{{ value_json.batt }}'
#  device_class: battery
#
- platform: mqtt
  name: "Kitchen Temperature"
  state_topic: "home/kitchen/temperature"
  unit_of_measurement: '°C'
  device_class: temperature
  availability_topic: "home/kitchen/status"
- platform: mqtt
  name: "Kitchen Humidity"
  state_topic: "home/kitchen/humidity"
  unit_of_measurement: '%'
  device_class: humidity
  availability_topic: "home/kitchen/status"
- platform: mqtt
  name: "Pressure"
  state_topic: "home/kitchen/pressure"
  unit_of_measurement: 'hPa'
  device_class: pressure
  availability_topic: "home/kitchen/status"

# Template sensors
- platform: template
  sensors:
    owm_pressure_mmhg:
      friendly_name: "OWM Pressure"
      unit_of_measurement: 'mmHg'
      device_class: pressure
      entity_id: sensor.owm_pressure
      value_template: >
        {% if states.sensor.owm_pressure.state is defined %}
          {{ (states('sensor.owm_pressure') | float / 1.33322) | round(0) }}
        {% else %}
          {{ states('sensor.owm_pressure_mmhg') }}
        {% endif %}
    pressure_mmhg:
      friendly_name: "Pressure"
      unit_of_measurement: 'mmHg'
      device_class: pressure
      entity_id: sensor.pressure
      value_template: >
        {% if states.sensor.pressure.state is defined %}
          {{ (states('sensor.pressure') | float / 1.33322) | round(2) }}
        {% else %}
          {{ states('sensor.pressure_mmhg') }}
        {% endif %}
