
# 17track packages tracker
- platform: seventeentrack
  username: !secret seventeentrack_email
  password: !secret seventeentrack_password

# MQTT sensors
#- platform: mqtt
#  state_topic: "owntracks/username/deviceid"
#  name: "Battery Tablet"
#  unit_of_measurement: "%"
#  value_template: '{{ value_json.batt }}'
#  device_class: battery
#
- platform: mqtt
  name: "Kitchen Temperature"
  state_topic: "home/kitchen/temperature"
  unit_of_measurement: '°C'
  device_class: temperature
  availability_topic: "home/kitchen/status"
- platform: mqtt
  name: "Kitchen Humidity"
  state_topic: "home/kitchen/humidity"
  unit_of_measurement: '%'
  device_class: humidity
  availability_topic: "home/kitchen/status"

# Template sensors
- platform: template
  sensors:
    owm_pressure_mmhg:
      friendly_name: "OWM Pressure"
      unit_of_measurement: 'mmHg'
      device_class: pressure
      entity_id: sensor.owm_pressure
      value_template: >
        {% if states.sensor.owm_pressure.state is defined %}
          {{ (states('sensor.owm_pressure') | float / 1.33322) | round(0) }}
        {% else %}
          {{ states('sensor.owm_pressure_mmhg') }}
        {% endif %}
    pressure_mmhg:
      friendly_name: "Pressure"
      unit_of_measurement: 'mmHg'
      device_class: pressure
      entity_id: sensor.pressure
      value_template: >
        {% if states.sensor.pressure.state is defined %}
          {{ (states('sensor.pressure') | float / 1.33322) | round(2) }}
        {% else %}
          {{ states('sensor.pressure_mmhg') }}
        {% endif %}
