- alias: Home Mode - Arriving
  initial_state: true
  trigger:
    - platform: state
      entity_id: binary_sensor.presence
      to: 'on'
  condition:
    - condition: numeric_state
      entity_id: sensor.ha_runtime_in_minutes
      above: 1
    - condition: state
      entity_id: input_select.house_mode
      state: 'Away'
  action:
    - service: input_select.select_option
      entity_id: input_select.house_mode
      data:
        option: 'Home'
  