- alias: Home Mode - Leaving
  initial_state: true
  trigger:
    - platform: state
      entity_id: binary_sensor.presence
      to: 'off'
      for:
        seconds: 15
  condition:
    - condition: numeric_state
      entity_id: sensor.ha_runtime_in_minutes
      above: 1
  action:
    - service: input_select.select_option
      entity_id: input_select.house_mode
      data:
        option: 'Away'
  