- alias: Home Mode - Vacation
  initial_state: true
  trigger:
    - platform: state
      entity_id: binary_sensor.presence
      to: 'off'
      for:
        hours: 24
  action:
    - service: input_select.select_option
      entity_id: input_select.house_mode
      data:
        option: 'Vacation'
