- alias: Good Morning - On
  initial_state: true
  trigger: 
    - platform: state
      entity_id: input_boolean.goodmorning_switch
      to: 'on'
  action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.goodmorning_switch
    - service: input_select.select_option
      entity_id: input_select.house_mode
      data:
        option: 'Home'
    - service: input_boolean.turn_off
      entity_id: input_boolean.goodnight_switch

- alias: Good Morning - Off
  initial_state: true
  trigger: 
    - platform: state
      entity_id: input_boolean.goodmorning_switch
      to: 'on'
      for:
        hours: 2
    - platform: time
      at: '12:00:00'
  action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.goodmorning_switch
