- alias: Security notification
  initial_state: true
  trigger:
    - platform: state
      entity_id: input_select.security_system
  action:
    - service: notify.all
      data_template:
        message: "Security mode set to {{ states('input_select.security_system') | upper }}"

- alias: Security - Arming
  initial_state: true
  trigger:
    - platform: state
      entity_id: input_select.house_mode
      to: 'Away'
    - platform: state
      entity_id: input_select.house_mode
      to: 'Vacation'
  action:
    - service: input_select.select_option
      entity_id: input_select.security_system
      data:
        option: 'Armed'

- alias: Security - Perimeter
  initial_state: true
  trigger:
    - platform: state
      entity_id: input_select.house_mode
      to: 'Night'
  action:
    - service: input_select.select_option
      entity_id: input_select.security_system
      data:
        option: 'Perimeter'

- alias: Security - Disarming
  initial_state: true
  trigger: 
    - platform: state
      entity_id: input_select.house_mode
      to: 'Home'
  condition:
    - condition: state
      entity_id: binary_sensor.presence
      state: 'on'
  action:
    - service: input_select.select_option
      entity_id: input_select.security_system
      data:
        option: 'Disarmed'
