


switch:
  - platform: template
    switches:
      cleaner:
        value_template: "{{ is_state('binary_sensor.cleaner', 'on') }}"
        turn_on:
          service: switch.turn_on
          data:
            entity_id: switch.cleaner_vacuum
        turn_off:
          service: switch.turn_off
          data:
            entity_id: switch.cleaner_vacuum
        icon_template: >-
          {% if is_state('binary_sensor.cleaner', 'on') %}
            mdi:broom
          {% else %}
            mdi:robot-vacuum
          {% endif %}


sensor:
  - platform: template
    sensors:
      cleaner_docked:
        friendly_name: 'Пылесос на Зарядке'
        entity_id: "binary_sensor.cleaner"
        value_template: >-
          {% if is_state("binary_sensor.cleaner", "on") %}
            Vacuuming
          {% elif is_state("binary_sensor.cleaner", "off")%}
            Docked
          {% else %}
            Unknown
          {% endif %}
        icon_template: >-
          {% if is_state("binary_sensor.cleaner", "on") %}
            mdi:login
          {% elif is_state("binary_sensor.cleaner", "off")%}
            mdi:page-layout-sidebar-right
          {% else %}
            mdi:comment-question-outline
          {% endif %}'


input_select:
  cleaner_mode:
    name: "Пылесос"
    options:
     - 'Waiting'
     - 'Vacuum Now'
     - 'Vacuuming'
     - 'Has Vacuumed'
     - 'Dock'
     - 'Not Today'
    icon: mdi:robot-vacuum


automation:
  - alias: '[House] Vacuum Ask When Everyone Is Away'
    initial_state: 'on'
    trigger:
      platform: time_pattern
      minutes: 5
      seconds: 00
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: group.persons
          state: 'not_home'
        - condition: time
          after: '09:00:00'
          before: '17:00:00'
        - condition: state
          entity_id: input_select.cleaner_mode
          state: 'Waiting'
        - condition: state
          entity_id: binary_sensor.cleaner
          state: 'off'
        - condition: state
          entity_id: input_boolean.cleaning_day
          state: 'off'
    action:
      - service: notify.hass_info
        data:
          message: 'Vacuum now?'
          title: 'No one seems to be at home'


  # - alias: '[House] Vacuum Now Selected'
  #   initial_state: 'on'
  #   trigger:
  #     platform: event
  #     event_type: ios.notification_action_fired
  #     event_data:
  #       actionName: VACUUM_NOW
  #   action:
  #     - service: homeassistant.turn_on
  #       entity_id: switch.cleaner
  #     - service: input_select.select_option
  #       data:
  #         entity_id: input_select.cleaner_mode
  #         option: 'Vacuuming'
  #     - service: notify.ios_isabellas_iphone_x
  #       data:
  #         message: 'Telling the Cleaner to start vacuuming'

  # - alias: '[House] Vacuum Snoozed Selected'
  #   initial_state: 'on'
  #   trigger:
  #     platform: event
  #     event_type: ios.notification_action_fired
  #     event_data:
  #       actionName: VACUUM_LATER
  #   action:
  #     - service: notify.ios_isabellas_iphone_x
  #       data:
  #         message: 'I will check again next hour'
  #         title: 'Not vacuuming right now'

  # - alias: '[House] Vacuum Stop Asking Selected'
  #   initial_state: 'on'
  #   trigger:
  #     platform: event
  #     event_type: ios.notification_action_fired
  #     event_data:
  #       actionName: VACUUM_STOP_ASKING
  #   action:
  #     - service: notify.ios_isabellas_iphone_x
  #       data:
  #         message: 'Got it'
  #         title: 'No vacuuming today'
  #     - service: input_select.select_option
  #       data:
  #         entity_id: input_select.cleaner_mode
  #         option: 'Not Today'

  ## Reset the vacuumed today check each night
  - alias: '[House] Vacuum Reset At Midnight'
    initial_state: 'on'
    trigger:
      platform: time
      at: '23:59:00'
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.cleaner_mode
          option: 'Waiting'
      - service: homeassistant.turn_off
        entity_id: switch.cleaner


  ## Not working
  - alias: '[House] Vacuum Dock Cleaner'
    initial_state: 'on'
    trigger:
      platform: state
      entity_id: input_select.cleaner_mode
      to: 'Dock'
    action:
      - service: homeassistant.turn_off
        entity_id: switch.cleaner
      - service: homeassistant.turn_off
        entity_id: switch.cleaner_living_room
      - delay: '0:01'
      - service: homeassistant.turn_on
        entity_id: switch.cleaner_dock
      - service: homeassistant.turn_on
        entity_id: switch.cleaner_dock_living_room
      - service: notify.ios_isabellas_iphone_x
        data:
          message: 'Trying to dock Cleaner'
      - service: input_select.select_option
        data:
          entity_id: input_select.cleaner_mode
          option: 'Waiting'


  - alias: '[House] Vacuum Now'
    initial_state: 'on'
    trigger:
      platform: state
      entity_id: input_select.cleaner_mode
      to: 'Vacuum Now'
    action:
      - service: homeassistant.turn_on
        entity_id: switch.cleaner

  - alias: '[House] Vacuum Starting'
    initial_state: 'on'
    trigger:
      platform: state
      entity_id: binary_sensor.cleaner
      to: 'on'
    action:
      - service: notify.hass_info
        data:
          message: 'Vacuuming'
      - service: input_select.select_option
        data:
          entity_id: input_select.cleaner_mode
          option: 'Vacuuming'

  - alias: '[House] Vacuum Is Done'
    initial_state: 'on'
    trigger:
      platform: state
      entity_id: binary_sensor.cleaner
      to: 'off'
    action:
      - service: notify.hass_info
        data:
          message: 'Vacuuming done'
      - service: input_select.select_option
        data:
          entity_id: input_select.cleaner_mode
          option: 'Has Vacuumed'
