input_select:
  day_mode:
    name: "Режим дня"
    options:
     - "Утро"
     - "День"
     - "Вечер"
     - "Ночь"
    icon: mdi:white-balance-sunny

sensor:
  - platform: time_date
    display_options:
      - 'time'
      - 'date'
      - 'date_time'
      # - 'time_date'
      # - 'time_utc'
  - platform: template
    sensors:
      date_day:
        entity_id: sensor.date
        value_template: >-
          {%- set months = ["янв", "фев", "мар", "апр", "мая", "июн", "июл", "авг", "сен", "окт", "ноя", "дек"] %}
          {%- set wdays = ["Пн", "Вт", "Ср", "Чт", "Пт", "Сб", "Вс"]  %}
          {{ wdays[now().weekday()] + ', ' + now().strftime('%d') + ' ' + months[now().month-1] }}          
    
group:
  owners_sleeping:
    name: "Хозяева спят"
    icon: mdi:sleep
    all: true
    entities:
      - binary_sensor.limych_sleeping

automation:
  ###################################
  ##  Set to morning               ##
  ###################################
  - alias: '[House] Day Mode To Morning'
    initial_state: 'on'
    trigger:
      - platform: sun
        event: sunrise

    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.day_mode
          option: "Утро"

  ###################################
  ##  Set to day                   ##
  ###################################
  - alias: '[House] Day Mode To Day'
    initial_state: 'on'
    trigger:
      - platform: time
        at: '10:00:00'

    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.day_mode
          option: "День"

  ###################################
  ##  Set to evening               ##
  ###################################
  - alias: '[House] Day Mode To Evening'
    initial_state: 'on'
    trigger:
      - platform: sun
        event: sunset
        offset: '-00:45:00'

    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.day_mode
          option: "Вечер"

  ###################################
  ##  Set to night                 ##
  ###################################
  - alias: '[House] Day Mode To Night'
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: group.owners_sleeping
        to: 'on'
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: input_select.day_mode
          state: "Вечер"
        ## Has to be between 22 and 06
        - condition: time
          after: '22:00:00'
          before: '06:00:00'
        ## Someone of owners has to be home
        - condition: state
          entity_id: binary_sensor.presence_owners
          state: 'on'

    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.day_mode
          option: "Ночь"
      - service: notify.all
        data:
          title: 'Сладких снов!'
          message: 'Похоже, все легли спать…'
