device_tracker:
  - platform: snmp
    host: !secret gateway_host_ip
    community: public
    baseoid: 1.3.6.1.2.1.4.22.1.2
    interval_seconds: 30
    consider_home: 120
  
  - platform: nmap_tracker
    hosts: !secret nmap_tracker_hosts
    scan_options: "-sn -T5 -n"
    interval_seconds: 30
    consider_home: 360
    home_interval: 3
    new_device_defaults:
      track_new_devices: true
      hide_if_away: true
    exclude:
      - !secret hass_host_ip
  
  #- platform: google_maps
  #  username: !secret google_location_username
  #  password: !secret google_location_password
  #  max_gps_accuracy: 150



automation:
  - alias: '[System] Hass New Device Tracked'
    initial_state: on
    trigger:
      platform: event
      event_type: device_tracker_new_device
    action:
      - service: notify.hass_info
        data_template:
          title: "New Device Tracked"
          message: "{{trigger.event.data.host_name}} ({{trigger.event.data.mac}})"
