homeassistant:
  customize:
    media_player.kitchen:
      friendly_name: "Колонки на кухне"
      icon: mdi:speaker-wireless
    media_player.living_room:
      friendly_name: "Колонки в гостиной"
      icon: mdi:speaker-wireless


ffmpeg:
  ffmpeg_bin: /usr/bin/ffmpeg


group:
  all_media_players:
    view: true
    icon: mdi:speaker-multiple
    entities:
      - media_player.kitchen
      - media_player.living_room

  all_speakers:
    view: true
    icon: mdi:speaker-multiple
    entities:
      - media_player.kitchen
      - media_player.living_room


media_player:
  - platform: linkplay
    devicename: "Kitchen"
    host: !secret speaker_kitchen_host
    lastfm_api_key: !secret lastfm_apikey
  - platform: linkplay
    devicename: "Living Room"
    host: !secret speaker_livingroom_host
    lastfm_api_key: !secret lastfm_apikey

  - platform: emby
    host: !secret emby_host
    api_key: !secret emby_apikey
    auto_hide: true


input_boolean:
  play_radio:
    name: "Радио"
    icon: mdi:radio


input_select:
  radio_station:
    name: "Радио-станция"
    options:
      # INPUT_BEGIN
      - Free Radio CW
      - Free Radio 80s
      - Absolute Radio
      - Absolute 80s
      - Absolute 90s
      - Heart
      - Heart 80s
      - Sleep Radio
      - Rai Radio 1
      - Rai Radio 2
      - Rai Radio 3
      - Rai Radio 4 Light
      - Rai Radio 5 Classica
      - Rai Raido 6 Teca
      - Rai Radio 7 Live
      - Rai Radio 8 Opera
      - Rai IsoRadio
      - Rai GrParlamento
      - RTL
      - RTL Best
      - RTL ItalianStyle
      - RTL Groove
      - RTL Lounge
      - RTL Radiofreccia
      - Radio Zeta L'Italiana
      - Radio Kiss Kiss
      - Radio Kiss Kiss Italia
      - Radio Kiss Kiss Napoli
      - RDS 100% Grandi Successi
      - Radio Deejay
      - R101 Diretta
      - Virgin Radio
      - Radio Capital
      - Radio 105
      - RMC Radio Monte Carlo
      - RMC2 Radio Monte Carlo 2
      - Radio m2o
      - Radio 24
      - Radio Ibiza
      - Discoradio
      - Radio Subasio
      - Radio Subasio +
      - Radio Suby
      - Radio Cuore
      - RIN Radio Italia Network
      - Radio RCS l’Onda Veronese
      - Ram Power 102.7
      - Radio Playstudio
      - Radio Studio Delta
      - Radio Sportiva
      - Studioradio – The Vintage Station
      - Radio Studio Più
      - RGS – Radio Grandi Successi
      - R.L.B.
      # INPUT_END
    icon: mdi:radio


automation:
  - alias: '[Media] Stop All Players at Night'
    initial_state: on
    trigger:
      - platform: state
        entity_id: input_select.day_mode
        to: 'Ночь'
      - platform: state
        entity_id: group.owners_sleeping_some
        to: 'on'
    action:
      - service: media_player.media_pause
        entity_id: all

  - alias: "[Media] Stop Radio when Movie is Playing"
    initial_state: on
    trigger:
      - platform: state
        entity_id: media_player.emby_emby_for_android_mobile_lenovo_tbx704l
        to: 'playing'
      - platform: state
        entity_id: media_player.emby_emby_mobile_chrome
        to: 'playing'
    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.play_radio

  - alias: '[Media] Play Radio'
    initial_state: on
    trigger:
      - platform: state
        entity_id: input_boolean.play_radio
        to: 'on'
      - platform: state
        entity_id: input_select.radio_station
    action:
      - service: input_boolean.turn_on
        entity_id: input_boolean.play_radio
      - service: media_player.play_media
        data_template:
          entity_id: group.all_speakers
          media_content_type: 'music'
          media_content_id: >-
            {# AUTOMATION_BEGIN #}
            {% if is_state("input_select.radio_station", "Free Radio CW") %} http://tx.whatson.com/http_live_bauer.php?i=freecoventry.aac&awparams=loggedin:false&amsparams=playerid:BMUK_tunein
            {% elif is_state("input_select.radio_station", "Free Radio 80s") %} http://tx.whatson.com/http_live_bauer.php?i=free80s.aac&awparams=loggedin:false&amsparams=playerid:BMUK_tunein
            {% elif is_state("input_select.radio_station", "Absolute Radio") %} http://player.absoluteradio.co.uk/tunein.php?i=ar24.aac
            {% elif is_state("input_select.radio_station", "Absolute 80s") %} http://player.absoluteradio.co.uk/tunein.php?i=a824.aac
            {% elif is_state("input_select.radio_station", "Absolute 90s") %} http://player.absoluteradio.co.uk/tunein.php?i=a924.aac
            {% elif is_state("input_select.radio_station", "Heart") %} http://media-ice.musicradio.com/HeartWestMids
            {% elif is_state("input_select.radio_station", "Heart 80s") %} http://media-ice.musicradio.com/Heart80s
            {% elif is_state("input_select.radio_station", "Sleep Radio") %} http://37.59.28.208:8453/stream
            {% elif is_state("input_select.radio_station", "Rai Radio 1") %} http://icestreaming.rai.it/1.mp3
            {% elif is_state("input_select.radio_station", "Rai Radio 2") %} http://icestreaming.rai.it/2.mp3
            {% elif is_state("input_select.radio_station", "Rai Radio 3") %} http://icestreaming.rai.it/3.mp3
            {% elif is_state("input_select.radio_station", "Rai Radio 4 Light") %} http://icestreaming.rai.it/4.mp3
            {% elif is_state("input_select.radio_station", "Rai Radio 5 Classica") %} http://icestreaming.rai.it/5.mp3
            {% elif is_state("input_select.radio_station", "Rai Raido 6 Teca") %} http://icestreaming.rai.it:80/9.mp3
            {% elif is_state("input_select.radio_station", "Rai Radio 7 Live") %} http://icestreaming.rai.it:80/10.mp3
            {% elif is_state("input_select.radio_station", "Rai Radio 8 Opera") %} http://icestreaming.rai.it:80/11.mp3
            {% elif is_state("input_select.radio_station", "Rai IsoRadio") %} http://icestreaming.rai.it/6.mp3
            {% elif is_state("input_select.radio_station", "Rai GrParlamento") %} http://icestreaming.rai.it/7.mp3
            {% elif is_state("input_select.radio_station", "RTL") %} http://shoutcast.rtl.it:3010/
            {% elif is_state("input_select.radio_station", "RTL Best") %} http://shoutcast.rtl.it:3020/
            {% elif is_state("input_select.radio_station", "RTL ItalianStyle") %} http://shoutcast.rtl.it:3030/
            {% elif is_state("input_select.radio_station", "RTL Groove") %} http://shoutcast.rtl.it:3040/
            {% elif is_state("input_select.radio_station", "RTL Lounge") %} http://shoutcast.rtl.it:3070/
            {% elif is_state("input_select.radio_station", "RTL Radiofreccia") %} http://shoutcast.rtl.it:3060/
            {% elif is_state("input_select.radio_station", "Radio Zeta L'Italiana") %} http://shoutcast.rtl.it:3030/stream/1/
            {% elif is_state("input_select.radio_station", "Radio Kiss Kiss") %} http://ice07.fluidstream.net:8080/KissKiss.mp3
            {% elif is_state("input_select.radio_station", "Radio Kiss Kiss Italia") %} http://wma07.fluidstream.net:3616/;stream.nsv
            {% elif is_state("input_select.radio_station", "Radio Kiss Kiss Napoli") %} http://ice08.fluidstream.net/KKNapoli.aac
            {% elif is_state("input_select.radio_station", "RDS 100% Grandi Successi") %} http://stream1.rds.it:8000/rds64k
            {% elif is_state("input_select.radio_station", "Radio Deejay") %} http://radiodeejay-lh.akamaihd.net/i/RadioDeejay_Live_1@189857/master.m3u8
            {% elif is_state("input_select.radio_station", "R101 Diretta") %} http://icecast.unitedradio.it/r101
            {% elif is_state("input_select.radio_station", "Virgin Radio") %} http://icecast.unitedradio.it/Virgin.mp3
            {% elif is_state("input_select.radio_station", "Radio Capital") %} http://radiocapital-lh.akamaihd.net/i/RadioCapital_Live_1@196312/master.m3u8
            {% elif is_state("input_select.radio_station", "Radio 105") %} http://icecast.105.net/105.mp3
            {% elif is_state("input_select.radio_station", "RMC Radio Monte Carlo") %} http://edge.radiomontecarlo.net/RMC.mp3
            {% elif is_state("input_select.radio_station", "RMC2 Radio Monte Carlo 2") %} http://edge.radiomontecarlo.net/MC2.mp3
            {% elif is_state("input_select.radio_station", "Radio m2o") %} http://radiom2o-lh.akamaihd.net/i/RadioM2o_Live_1@42518/master.m3u8
            {% elif is_state("input_select.radio_station", "Radio 24") %} http://shoutcast.radio24.it:8000/listen.pls
            {% elif is_state("input_select.radio_station", "Radio Ibiza") %} http://wma02.fluidstream.net:5010/
            {% elif is_state("input_select.radio_station", "Discoradio") %} http://46.37.20.206:1935/live/1discoradio.stream/playlist.m3u8
            {% elif is_state("input_select.radio_station", "Radio Subasio") %} http://icy.unitedradio.it/Subasio.mp3
            {% elif is_state("input_select.radio_station", "Radio Subasio +") %} http://icy.unitedradio.it/SubasioPiu.mp3
            {% elif is_state("input_select.radio_station", "Radio Suby") %} https://icecast.unitedradio.it/Suby.mp3
            {% elif is_state("input_select.radio_station", "Radio Cuore") %} http://nr9.newradio.it:9029/
            {% elif is_state("input_select.radio_station", "RIN Radio Italia Network") %} http://sr9.inmystream.info:8006/
            {% elif is_state("input_select.radio_station", "Radio RCS l’Onda Veronese") %} http://176.31.254.217:8030/
            {% elif is_state("input_select.radio_station", "Ram Power 102.7") %} http://46.37.20.206:1935/live/1ram.stream/playlist.m3u8
            {% elif is_state("input_select.radio_station", "Radio Playstudio") %} http://playstudio.serverroom.us:4140/
            {% elif is_state("input_select.radio_station", "Radio Studio Delta") %} http://5.63.145.172:7203/
            {% elif is_state("input_select.radio_station", "Radio Sportiva") %} http://nr5.newradio.it:8545/stream.mp3
            {% elif is_state("input_select.radio_station", "Studioradio – The Vintage Station") %} http://91.121.38.216:8060/
            {% elif is_state("input_select.radio_station", "Radio Studio Più") %} http://ice.studiopiu.net/rete.aac
            {% elif is_state("input_select.radio_station", "RGS – Radio Grandi Successi") %} http://nrf1.newradio.it:9746/stream?type=http&nocache=8279
            {% elif is_state("input_select.radio_station", "R.L.B.") %} http://nr5.newradio.it:8767/stream.mp3
            {# AUTOMATION_END #}
            {% endif %}

  - alias: "[Media] Stop Radio"
    initial_state: on
    trigger:
      - platform: state
        entity_id: input_boolean.play_radio
        to: 'off'
      - platform: state
        entity_id: media_player.kitchen
        to: 'paused'
        for:
          seconds: 20
      - platform: state
        entity_id: media_player.living_room
        to: 'paused'
        for:
          seconds: 20
    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.play_radio
      - service: media_player.media_pause
        entity_id: group.all_speakers

  - alias: "[Media] Play Radio on Wake"
    initial_state: on
    trigger:
      - platform: state
        entity_id: group.motion
        to: 'on'
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: input_boolean.play_radio
          state: 'off'
          for:
            hours: 5
        - condition: state
          entity_id: input_select.day_mode
          state: 'Утро'
        - condition: state
          entity_id: input_boolean.guest_mode
          state: 'off'
    action:
      - service: notify.all
        data:
          message: 'С добрым утром!'
      - service: media_player.volume_set
        data:
          entity_id: all
          volume_level: 0.30
      - service: automation.trigger
        entity_id: automation.media_play_radio
