homeassistant:
  customize:
    media_player.kitchen:
      friendly_name: "Колонки на кухне"
      icon: mdi:speaker-wireless
    media_player.living_room:
      friendly_name: "Колонки в гостиной"
      icon: mdi:speaker-wireless


ffmpeg:
  ffmpeg_bin: /usr/bin/ffmpeg


group:
  all_media_players:
    view: true
    icon: mdi:speaker-multiple
    entities:
      - media_player.kitchen
      - media_player.living_room

  all_speakers:
    view: true
    icon: mdi:speaker-multiple
    entities:
      - media_player.kitchen
      - media_player.living_room


media_player:
  - platform: linkplay
    devicename: "Kitchen"
    host: !secret speaker_kitchen_host
    lastfm_api_key: !secret lastfm_apikey
  - platform: linkplay
    devicename: "Living Room"
    host: !secret speaker_livingroom_host
    lastfm_api_key: !secret lastfm_apikey

  - platform: emby
    host: !secret emby_host
    api_key: !secret emby_apikey
    auto_hide: true


plex:
  host: !secret plex_host
  token: !secret plex_apikey


input_boolean:
  play_radio:
    name: "Радио"
    icon: mdi:radio


input_select:
  radio_station:
    name: "Радио-станция"
    options:
      # INPUT_BEGIN
      - "Radio Subasio +"
      # INPUT_END
    icon: mdi:radio


automation:
  - alias: '[Media] Stop All Players at Night'
    initial_state: on
    trigger:
      - platform: state
        entity_id: input_select.day_mode
        to: 'Ночь'
      - platform: state
        entity_id: group.sleeping_owners_some
        to: 'on'
    action:
      - service: media_player.media_pause
        entity_id: all

  - alias: "[Media] Stop Radio when Movie is Playing"
    initial_state: on
    trigger:
      - platform: state
        entity_id: media_player.emby_emby_for_android_mobile_lenovo_tbx704l
        to: 'playing'
      - platform: state
        entity_id: media_player.emby_emby_mobile_chrome
        to: 'playing'
      - platform: state
        entity_id: media_player.emby_emby_mobile_chrome_3
        to: 'playing'
      - platform: state
        entity_id: media_player.plex_notebook
        to: 'playing'
      - platform: state
        entity_id: media_player.plex_willy
        to: 'playing'
    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.play_radio

  - alias: '[Media] Play Radio'
    initial_state: on
    trigger:
      - platform: state
        entity_id: input_boolean.play_radio
        to: 'on'
      - platform: state
        entity_id: input_select.radio_station
    action:
      - service: input_boolean.turn_on
        entity_id: input_boolean.play_radio
      - service: media_player.play_media
        data_template:
          entity_id: group.all_speakers
          media_content_type: 'music'
          media_content_id: >-
            {# AUTOMATION_BEGIN #}
            {% if is_state("input_select.radio_station", "Radio Subasio +") %}http://icy.unitedradio.it/SubasioPiu.mp3
            {# AUTOMATION_END #}
            {% endif %}

  - alias: "[Media] Stop Radio"
    initial_state: on
    trigger:
      - platform: state
        entity_id: input_boolean.play_radio
        to: 'off'
      - platform: state
        entity_id: media_player.kitchen
        to: 'paused'
        for:
          seconds: 20
      - platform: state
        entity_id: media_player.living_room
        to: 'paused'
        for:
          seconds: 20
    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.play_radio
      - service: media_player.media_pause
        entity_id: group.all_speakers

  - alias: "[Media] Set base volume"
    initial_state: on
    trigger: []
    action:
      - service: media_player.volume_set
        data:
          entity_id: group.all_speakers
          volume_level: 0.30

  - alias: "[Media] Play Radio on Wake"
    initial_state: on
    trigger:
      - platform: state
        entity_id: group.motion
        to: 'on'
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: input_boolean.play_radio
          state: 'off'
          for:
            hours: 5
        - condition: state
          entity_id: input_select.day_mode
          state: 'Утро'
        - condition: state
          entity_id: input_boolean.guest_mode
          state: 'off'
    action:
      - service: notify.all
        data:
          message: 'С добрым утром!'
      - service: automation.trigger
        entity_id: automation.media_set_base_volume
      - service: automation.trigger
        entity_id: automation.media_play_radio
