homeassistant:
  customize:
    sensor.limych_sleeping:
      friendly_name: "Лимыч спит"
      icon: mdi:sleep
    device_tracker.limych_presence:
      friendly_name: "Присутствие Лимыча"
      icon: mdi:map-marker-circle

sensor:
  - platform: mqtt
    name: limych_sleeping
    state_topic: 'sleep/limych/tracking'

input_boolean:
  limych_home:
    name: Limych Homekit
#    icon: mdi:
