# group:
#   motion:
#     name: motion
#     entities:
#       - binary_sensor.home_occupancy


sensor:
  - platform: mqtt
    state_topic: 'monitor/home/status'
    name: "Статус мониторинга"


binary_sensor:
  - platform: template
    sensors:
      presence_owners:
        friendly_name: "Хозяева в Доме"
        device_class: occupancy
        value_template: >-
          {{ is_state('person.limych', 'home') }}

      presence:
        friendly_name: "Люди в Доме"
        device_class: occupancy
        value_template: >-
          {{ is_state('binary_sensor.presence_owners', 'on')
          or is_state('input_boolean.guest_mode', 'on') }}
        #   or is_state('group.motion', 'on') }}


automation:
  - alias: '[Presence] Presence MQTT event'
    initial_state: 'on'
    trigger:
    - platform: mqtt
      topic: 'monitor/home/#'
    action:
      event: HASS_MQTT_PRESENCE
      event_data_template:
        topic: '{{ trigger.topic }}'
        payload: '{{ trigger.payload }}'
