homeassistant:
  customize_glob:
    device_tracker.*_bt:
      source_type: bluetooth
    sensor.*_bt:
      source_type: bluetooth


group:
  motion:
    name: "Движение в доме"
    all: false
    entities:
      - binary_sensor.front_door
      - binary_sensor.hallway_motion
      - binary_sensor.kitchen_motion
      # - binary_sensor.wallpanel_motion


sensor:
  - platform: mqtt
    state_topic: 'presence/hallway/status'
    name: Monitor Hallway

  - platform: mqtt
    state_topic: 'presence/bedroom/status'
    name: Monitor Bedroom


binary_sensor:
  - platform: template
    sensors:
      presence_owners:
        friendly_name: "Хозяева в Доме"
        device_class: occupancy
        value_template: >-
          {{ is_state('person.limych', 'home') }}

      presence:
        friendly_name: "Люди в Доме"
        device_class: occupancy
        value_template: >-
          {{ is_state('binary_sensor.presence_owners', 'on')
          or is_state('input_boolean.guest_mode', 'on')
          or is_state('group.motion', 'on') }}


automation:
  - alias: '[Presence] Initialize on Hass Started'
    initial_state: on
    trigger:
      - platform: homeassistant
        event: start
    action:
      - service: mqtt.publish
        data:
          topic: "presence/scan/restart"

  # - alias: '[Presence] Presence MQTT event'
  #   initial_state: on
  #   trigger:
  #     - platform: mqtt
  #       topic: 'presence/#'
  #   action:
  #     event: HASS_MQTT_PRESENCE
  #     event_data_template:
  #       topic: '{{ trigger.topic }}'
  #       payload: '{{ trigger.payload }}'

  - alias: '[Presence] Owners presence On'
    initial_state: on
    trigger:
      - platform: state
        entity_id: binary_sensor.presence_owners
        to: 'on'
    condition:
      - condition: numeric_state
        entity_id: sensor.uptime
        above: 1
    action:
      - service: notify.limych
        data_template:
          message: "Добро пожаловать домой!"

  - alias: '[Presence] Owners presence Off'
    initial_state: on
    trigger:
      - platform: state
        entity_id: binary_sensor.presence_owners
        to: 'off'
    condition:
      - condition: numeric_state
        entity_id: sensor.uptime
        above: 1
    action:
      - service: notify.limych
        data_template:
          message: "Счастливого пути!"
