homeassistant:
  customize:
    sensor.monitor:
      friendly_name: "Статус мониторинга"


group:
  motion:
    name: motion
    entities:
      - binary_sensor.front_door
      - binary_sensor.hallway_motion
      - binary_sensor.kitchen_motion
      # - binary_sensor.wallpanel_motion


sensor:
  - platform: mqtt
    state_topic: 'presence/hassio/status'
    name: monitor


binary_sensor:
  - platform: template
    sensors:
      presence_owners:
        friendly_name: "Хозяева в Доме"
        device_class: occupancy
        value_template: >-
          {{ is_state('person.limych', 'home') }}

      presence:
        friendly_name: "Люди в Доме"
        device_class: occupancy
        value_template: >-
          {{ is_state('binary_sensor.presence_owners', 'on')
          or is_state('input_boolean.guest_mode', 'on')
          or is_state('group.motion', 'on') }}


automation:
  - alias: '[Presence] Presence MQTT event'
    initial_state: on
    trigger:
    - platform: mqtt
      topic: 'presence/#'
    action:
      event: HASS_MQTT_PRESENCE
      event_data_template:
        topic: '{{ trigger.topic }}'
        payload: '{{ trigger.payload }}'

  - alias: '[Presence] Owners presence On'
    initial_state: on
    trigger:
      - platform: state
        entity_id: binary_sensor.presence_owners
        to: 'on'
    condition:
      - condition: numeric_state
        entity_id: sensor.uptime
        above: 1
    action:
      - service: notify.limych
        data_template:
          message: "Добро пожаловать домой!"

  - alias: '[Presence] Owners presence Off'
    initial_state: on
    trigger:
      - platform: state
        entity_id: binary_sensor.presence_owners
        to: 'off'
    condition:
      - condition: numeric_state
        entity_id: sensor.uptime
        above: 1
    action:
      - service: notify.limych
        data_template:
          message: "Счастливого пути!"
