homeassistant:
  customize:
    sensor.owm_temperature:
      friendly_name: "На улице"

  customize_glob:
    sensor.kitchen_*:
      friendly_name: "Кухня"
    sensor.*temperature*:
      templates:
        hs_color: >-
          if (state > 25) return [0, 85];
          else if (state > 23) return [40, 70];
          else return [0, 0];


binary_sensor:
  - platform: template
    sensors:
      dark_outside:
        friendly_name: "Темно на улице"
        value_template: >-
          {{ is_state('sun.sun', 'below_horizon') }}

sensor:
  # - platform: mqtt
  #   state_topic: "owntracks/username/deviceid"
  #   name: "Battery Tablet"
  #   unit_of_measurement: "%"
  #   value_template: '{{ value_json.batt }}'
  #   device_class: battery
  
  - platform: mqtt
    name: kitchen_temperature
    state_topic: "sensor/kitchen/temperature"
    unit_of_measurement: '°C'
    device_class: temperature
    availability_topic: "sensor/kitchen/status"
  - platform: mqtt
    name: kitchen_humidity
    state_topic: "sensor/kitchen/humidity"
    unit_of_measurement: '%'
    device_class: humidity
    availability_topic: "sensor/kitchen/status"
