homeassistant:
  customize:
    sensor.kitchen_temperature:
      friendly_name: Кухня
    sensor.owm_temperature:
      friendly_name: На улице

    sensor.kitchen_humidity:
      friendly_name: Кухня

#    sensor.illumination_158d0001a66256:
#      friendly_name: Hallway Lux
#      icon: mdi:theme-light-dark


  customize_glob:
    sensor.*temperature*:
      templates:
        hs_color: >
          if (state < 23) return [0, 0];
          else if (state > 23) return [40, 70];
          else if (state > 25) return [0, 85];
