homeassistant:
  customize_glob:
    sensor.*_humidity:
      device_class: humidity
      unit_of_measurement: '%'
    sensor.*_temperature:
      device_class: temperature
      unit_of_measurement: '°C'
      # templates:
      #   hs_color: >-
      #     if (state > 25) return [0, 85];
      #     else if (state > 23) return [40, 70];
      #     else return [0, 0];
    #
    sensor.kitchen_*:
      friendly_name: "Кухня"


binary_sensor:
  - platform: template
    sensors:
      dark_outside:
        friendly_name: "Темно на улице"
        value_template: >-
          {{ is_state('sun.sun', 'below_horizon') }}

sensor:
  - platform: mqtt
    name: kitchen_temperature
    state_topic: "sensor/kitchen/temperature"
    availability_topic: "sensor/kitchen/status"
  - platform: mqtt
    name: kitchen_humidity
    state_topic: "sensor/kitchen/humidity"
    availability_topic: "sensor/kitchen/status"
