input_boolean:
  test:
    name: Test stuff
    initial: off

sensor:
  - platform: openweathermap
    api_key: !secret openweathermap_apikey
    monitored_conditions:
      - temperature

  - platform: average_temperature
    name: "Average Temperature Test"
    duration:
      days: 2
    entities:
      - weather.gismeteo
      - sensor.owm_temperature
