homeassistant:
  customize_glob:
    sensor.*pressure*:
      friendly_name: "Атм. Давление"
      icon: mdi:gauge
    sensor.*humidity*:
      icon: mdi:water-percent

weather:
  - platform: openweathermap
    api_key: !secret openweathermap_apikey
#  - platform: yandex
#    api_key: !secret yandex_apikey
#  - platform: gismeteo

sensor:
  - platform: openweathermap
    api_key: !secret openweathermap_apikey
    language: ru
    forecast: true
    monitored_conditions:
      - weather
      - temperature
      - wind_speed
      - wind_bearing
      - humidity
      - pressure
      - clouds
      - rain
      - snow
      - weather_code

#  - platform: yr
#    Name: Погода

  - platform: mqtt
    name: pressure
    state_topic: "sensor/kitchen/pressure"
    unit_of_measurement: 'hPa'
    device_class: pressure
    availability_topic: "sensor/kitchen/status"

  - platform: mqtt
    name: pressure_mmhg
    state_topic: "sensor/kitchen/pressure_mmhg"
    unit_of_measurement: 'mmHg'
    device_class: pressure
    availability_topic: "sensor/kitchen/status"

  # Template sensors
  - platform: template
    sensors:
      owm_pressure_mmhg:
        friendly_name: "OWM Pressure"
        unit_of_measurement: 'mmHg'
        device_class: pressure
        entity_id: sensor.owm_pressure
        value_template: >
          {% if states.sensor.owm_pressure.state is defined %}
            {{ (states('sensor.owm_pressure') | float / 1.33322) | round(0) }}
          {% else %}
            {{ states('sensor.owm_pressure_mmhg') }}
          {% endif %}


camera:
  - platform: generic
    name: "Moscow meteogram"
    still_image_url: https://www.yr.no/place/Russia/Moscow/Moscow/meteogram.svg
    content_type: 'image/svg+xml'
