homeassistant:
  customize:
    sensor.pressure:
      friendly_name: "Атм. Давление"

weather:
  - platform: openweathermap
    api_key: !secret openweathermap_apikey
#  - platform: yandex
#    api_key: !secret yandex_apikey
#  - platform: gismeteo

sensor:
  - platform: openweathermap
    api_key: !secret openweathermap_apikey
    language: ru
    forecast: true
    monitored_conditions:
      - weather
      - temperature
      - wind_speed
      - wind_bearing
      - humidity
      - pressure
      - clouds
      - rain
      - snow
      - weather_code

#  - platform: yr
#    Name: Погода

  - platform: mqtt
    name: pressure
    state_topic: "home/kitchen/pressure"
    unit_of_measurement: 'hPa'
    device_class: pressure
    availability_topic: "home/kitchen/status"

camera:
  - platform: generic
    name: "Moscow meteogram"
    still_image_url: https://www.yr.no/place/Russia/Moscow/Moscow/meteogram.svg
    content_type: 'image/svg+xml'