homeassistant:
  customize_glob:
    sensor.*pressure*:
      device_class: pressure
      icon: mdi:gauge
    sensor.*humidity*:
      icon: mdi:water-percent

weather:
  - platform: gismeteo
  - platform: gismeteo
    name: "Gismeteo Daily"
    mode: daily
    
binary_sensor:
  - platform: car_wash
    weather: weather.gismeteo_daily

sensor:
  - platform: gismeteo
    forecast: true
    monitored_conditions:
      - weather
      - temperature
      - wind_speed
      - wind_bearing
      - humidity
      - pressure
      - clouds
      - rain
      - snow
      - storm
      - geomagnetic

  - platform: mqtt
    name: pressure
    state_topic: "sensor/kitchen/pressure"
    unit_of_measurement: 'hPa'
    availability_topic: "sensor/kitchen/status"
  - platform: mqtt
    name: pressure_mmhg
    state_topic: "sensor/kitchen/pressure_mmhg"
    unit_of_measurement: 'mmHg'
    availability_topic: "sensor/kitchen/status"
    
  - platform: average_temperature
    duration:
      days: 2
    entities:
      - sensor.gismeteo_temperature

  - platform: airvisual
    api_key: !secret airvisual_apikey
    monitored_conditions:
      - us
    show_on_map: false

camera:
  - platform: generic
    name: "Moscow meteogram"
    still_image_url: https://www.foreca.ru/meteogram.php?loc_id=100819827&lang=ru
    content_type: 'image/png'


automation:
  - alias: '[Misc] When I can Clear the Car'
    initial_state: 'on'
    trigger:
      - entity_id: binary_sensor.car_wash
        platform: state
        from: 'off'
        to: 'on'
    action:
      - service: notify.limych
        data_template:
          message: "Пора запланировать мойку машины."
        
