weather:
  - platform: gismeteo
  - platform: gismeteo
    name: "Gismeteo Daily"
    mode: daily


sensor:
  - platform: gismeteo
    forecast: true
    monitored_conditions:
      - weather
      - temperature
      - wind_speed
      - wind_bearing
      - humidity
      - pressure
      - clouds
      - rain
      - snow
      - storm
      - geomagnetic

  - platform: template
    sensors:
      gismeteo_pressure_mmhg:
        unit_of_measurement: 'mmHg'
        friendly_name: "Gismeteo Pressure"
        value_template: >-
          {% if states.sensor.gismeteo_pressure %}
            {{ (states('sensor.gismeteo_pressure') | float / 1.33322) | round(1) }}
          {% endif %}

  - platform: average
    name: 'Average Temperature'
    duration:
      days: 3
    entities:
      - sensor.gismeteo_temperature

  - platform: airvisual
    api_key: !secret airvisual_apikey
    monitored_conditions:
      - us
    show_on_map: false


camera:
  - platform: generic
    name: "Moscow meteogram"
    still_image_url: https://www.foreca.ru/meteogram.php?loc_id=100819827&lang=ru
    content_type: 'image/png'
