homeassistant:
  customize_glob:
    sensor.system_*:
      icon: mdi:server-network
      templates:
        hs_color: >-
          if (state === 'Online') return [0, 0];
          else if (state === 'Offline') return [0, 85];
          else return [40, 70];
    sensor.system_security_*:
      icon: mdi:security
    sensor.system_pc_*:
      icon: mdi:laptop
    sensor.system_media_*:
      icon: mdi:speaker

  customize:
    sensor.connection_internet:
      icon: mdi:wan
    sensor.system_uplink:
      icon: mdi:wan
    sensor.system_gateway:
      icon: mdi:server
    sensor.system_nas:
      icon: mdi:nas
    sensor.connection_wifi_ap:
      icon: mdi:access-point
    sensor.connection_lan_router:
      icon: mdi:router-wireless
    sensor.system_server_emby:
      icon: mdi:emby
    sensor.system_server_transmission:
      icon: mdi:download
    sensor.system_server_repo:
      icon: mdi:git
    sensor.system_server_syncthing:
      icon: mdi:cloud-sync
    sensor.system_server_sonarr:
      icon: mdi:cloud-search
    #
    sensor.system_security_intercom:
      icon: mdi:cctv
    #
    sensor.system_cleaner:
      icon: mdi:robot-vacuum
    #
    input_boolean.test:
      icon: mdi:test-tube


input_boolean:
  test:
    name: "Test stuff"
    initial: off


sensor:
  - platform: template
    sensors:
      connection_internet:
        friendly_name: "Интернет"
        entity_id: binary_sensor.internet
        value_template: >-
          {{ 'Online' if is_state('binary_sensor.internet', 'on') else 'Offline' }}
      system_uplink:
        friendly_name: "Uplink"
        entity_id: device_tracker.uplink
        value_template: >-
          {{ 'Online' if is_state('device_tracker.uplink', 'home') else 'Offline' }}
      system_gateway:
        friendly_name: "Gateway"
        entity_id: device_tracker.server_gate_uplink
        value_template: >-
          {{ 'Online' if is_state('device_tracker.server_gate_uplink', 'home') else 'Offline' }}
      system_nas:
        friendly_name: "NAS"
        entity_id: device_tracker.server_nas
        value_template: >-
          {{ 'Online' if is_state('device_tracker.server_nas', 'home') else 'Offline' }}
      connection_wifi_ap:
        friendly_name: "WiFi точка доступа"
        entity_id: device_tracker.lan_wifi_ap
        value_template: >-
          {{ 'Online' if is_state('device_tracker.lan_wifi_ap', 'home') else 'Offline' }}
      connection_lan_router:
        friendly_name: "OpenWRT роутер"
        entity_id: device_tracker.lan_router
        value_template: >-
          {{ 'Online' if is_state('device_tracker.lan_router', 'home') else 'Offline' }}
      system_server_emby:
        friendly_name: "Emby"
        entity_id: device_tracker.server_emby
        value_template: >-
          {{ 'Online' if is_state('device_tracker.server_emby', 'home') else 'Offline' }}
      system_server_transmission:
        friendly_name: "Transmission"
        entity_id: device_tracker.server_transmission
        value_template: >-
          {{ 'Online' if is_state('device_tracker.server_transmission', 'home') else 'Offline' }}
      system_server_repo:
        friendly_name: "GIT Repository"
        entity_id: device_tracker.server_repo
        value_template: >-
          {{ 'Online' if is_state('device_tracker.server_repo', 'home') else 'Offline' }}
      system_server_syncthing:
        friendly_name: "Syncthing"
        entity_id: device_tracker.server_syncthing
        value_template: >-
          {{ 'Online' if is_state('device_tracker.server_syncthing', 'home') else 'Offline' }}
      system_server_sonarr:
        friendly_name: "Sonarr & Jackett"
        entity_id: device_tracker.server_sonarr
        value_template: >-
          {{ 'Online' if is_state('device_tracker.server_sonarr', 'home') else 'Offline' }}

      system_security_intercom:
        friendly_name: "Домофон"
        entity_id: device_tracker.security_intercom
        value_template: >-
          {{ 'Online' if is_state('device_tracker.security_intercom', 'home') else 'Offline' }}

      system_pc_willy:
        friendly_name: "Willy"
        entity_id: device_tracker.limych_willy
        value_template: >-
          {{ 'Online' if is_state('device_tracker.limych_willy', 'home') else 'Offline' }}

      system_media_kitchen:
        friendly_name: "Колонки на Кухне"
        entity_id: device_tracker.media_kitchen
        value_template: >-
          {{ 'Online' if is_state('device_tracker.media_kitchen', 'home') else 'Offline' }}
      system_media_living_room:
        friendly_name: "Колонки В Гостиной"
        entity_id: device_tracker.media_living_room
        value_template: >-
          {{ 'Online' if is_state('device_tracker.media_living_room', 'home') else 'Offline' }}

      system_cleaner:
        friendly_name: "Пылесос"
        entity_id: device_tracker.cleaner
        value_template: >-
          {{ 'Online' if is_state('device_tracker.cleaner', 'home') else 'Offline' }}


automation:
  - alias: '[System] Device Status'
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id:
          - sensor.connection_internet
          - sensor.system_uplink
          - sensor.system_gateway
          - sensor.system_nas
          - sensor.connection_wifi_ap
          - sensor.connection_lan_router
          - sensor.system_server_emby
          - sensor.system_server_transmission
          - sensor.system_server_repo
          - sensor.system_server_syncthing
          - sensor.system_server_sonarr
          - sensor.system_security_intercom
        to: 'Offline'
        for:
          minutes: 5
    action:
      - service: notify.hass_info
        data_template:
          title: 'Device {{ trigger.to_state.name }} is'
          message: '"{{ trigger.to_state.state }}"'
