sensor:
  - platform: uptime
    name: Uptime
    unit_of_measurement: minutes
  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: /
      - type: memory_free
      - type: memory_use_percent
      - type: processor_use
      - type: last_boot
  - platform: version
  - platform: version
    name: version_available
    source: hassio

  - platform: glances
    host: !secret hass_host_ip
    name: "Nuc"
    version: 3
    resources:
      - 'disk_use_percent'
      - 'memory_use_percent'
      - 'swap_use_percent'
      - 'processor_load'
      - 'docker_active'
      - 'docker_cpu_use'

rest_command:
  google_backup:
    url: 'http://localhost:8055/gb/doBackup'
    timeout: '300'

automation:
  - alias: '[System] Hass Started'
    initial_state: 'on'
    trigger:
      platform: homeassistant
      event: start
    action:
      - service: frontend.set_theme
        data:
          name: midnight
      - service: notify.hass_info
        data:
          message: "Hass.io Online"

  - alias: '[System] Hass Stopped'
    initial_state: 'on'
    trigger:
      platform: homeassistant
      event: shutdown
    action:
      - service: notify.hass_info
        data:
          message: "Hass.io Offline"

  - alias: '[System] Hass New Device Tracked'
    trigger:
      platform: event
      event_type: device_tracker_new_device
    action:
      - service: notify.hass_info
        data_template:
          message: >
            New Device Tracked: {{trigger.event.data.host_name}} ({{trigger.event.data.entity_id}})

  - alias: '[System] Hass Updater'
    trigger:
      - platform: state
        entity_id: sensor.version_available
    condition:
      - condition: template
        value_template: >-
          {{
            states('sensor.version_available')
            !=
            states('sensor.version_current')
          }}
    action:
      - service: notify.hass_info
        data_template:
          title: Upgrade time!
          message: >-
            Hass.io version {{ states('sensor.version_available') }} is now available!
          data:
            attachment:
              content-type: png
              url: https://png2.kisspng.com/20180504/avq/kisspng-computer-icons-starburst-clip-art-the-store-to-upgrade-kuangshuai-5aecf79d6760f6.2104595515254793254235.png

  - alias: '[System] Weekly Backup Monday at 3:00'
    trigger:
      platform: time
      at: '03:00'
#    condition:
#      - condition: time
#        weekday:
#          - mon
    action:
      - service: hassio.snapshot_full
        data_template:
          name: "Automated Snapshot {{ now().strftime('%Y-%m-%d') }}"
      - service: notify.hass_info
        data_template:
          message: "Automated Snapshot {{ now().strftime('%Y-%m-%d') }}"

  - alias: '[System] Weekly Backup Monday to Google at 3:30'
    trigger:
      - platform: time
        at: '03:30'
#    condition:
#      - condition: time
#        weekday:
#          - mon
    action:
      - service: rest_command.google_backup
      - service: notify.hass_info
        data:
          message: "Automatic snapshot uploaded"

  - alias: '[System] IP Ban Notify'
    trigger:
      - platform: state
        entity_id: persistent_notification.ipban
    condition:
      - condition: template
        value_template: "{{ trigger.to_state.state != off }}"
    action:
      - service: notify.hass_info
        data_template:
          message: "{{ trigger.state.attributes.message }}. IP address has been banned."
